### ISSUE TITLE
If the user is valided but doesn't belong to a workshop . . .

### ISSUE THREAD

**Issue by MilcahHalili** [MilcahHalili/litkit-ui-preview#83]
. . . then, if the user refreshed the page, it hangs on the loading component.

User should still see the pending verification view unless a workshop has been assigned to them.

Let's get rid of the isVerified boolean check from the conditional logic in the UI to simplify the solution:

- [x] Render the workshop index once the user is added to a workshop.
- [x] Delete the isVerified boolean data type from Prisma schema.
- [x] Run the migration with `npx prisma db push`

**Comment by H-b8** [comment]
Will run migrations and PR after categories is merged so I don't drop new columns from the db
